apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nami-backend-prod
  namespace: nami-backend-prod
spec:
  dnsNames:
    - api.nami.gg
  secretName: nami-backend-tls-prod
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer